export const categoryLinks = [
    {
      image: "https://a0.muscache.com/pictures/3b1eb541-46d9-4bef-abc4-c37d77e3c21b.jpg",
      label: "Apartments",
    },
    {
      image: "https://a0.muscache.com/pictures/248f85bf-e35e-4dc3-a9a1-e1dbff9a3db4.jpg",
      label: "Lakefront",
    },
    {
      image: "https://a0.muscache.com/pictures/aaa02c2d-9f0d-4c41-878a-68c12ec6c6bd.jpg",
      label: "Cabins",
    },

    {
      image: "https://a0.muscache.com/pictures/677a041d-7264-4c45-bb72-52bff21eb6e8.jpg",
      label: "Camping",
    },
    {
      image: "https://a0.muscache.com/pictures/eb7ba4c0-ea38-4cbb-9db6-bdcc8baad585.jpg",
      label: "Skiing",
    },
    {
      image: "https://a0.muscache.com/pictures/c0fa9598-4e37-40f3-b734-4bd0e2377add.jpg",
      label: "Iconic City",
    },
    {
      image: "https://a0.muscache.com/pictures/3fb523a0-b622-4368-8142-b5e03df7549b.jpg",
      label: "Boates",
    },
    {
      image: "https://a0.muscache.com/pictures/3726d94b-534a-42b8-bca0-a0304d912260.jpg",
      label: "Luxe",
    },
    {
      image: "https://a0.muscache.com/pictures/bcd1adc0-5cee-4d7a-85ec-f6730b0f8d0c.jpg",
      label: "House Boats",
    },
    {
      image: "https://a0.muscache.com/pictures/c5a4f6fc-c92c-4ae8-87dd-57f1ff1b89a6.jpg",
      label: "Domes",
    },
    {
      image: "https://a0.muscache.com/pictures/33dd714a-7b4a-4654-aaf0-f58ea887a688.jpg",
      label: "Vineyard's hut",
    },
    {
      image: "https://a0.muscache.com/pictures/33dd714a-7b4a-4654-aaf0-f58ea887a688.jpg",
      label: "Riads",
    },
    {
      image: "https://a0.muscache.com/pictures/ee9e2a40-ffac-4db9-9080-b351efc3cfc4.jpg",
      label: "Island",
    },
    {
        image: "https://a0.muscache.com/pictures/aaa02c2d-9f0d-4c41-878a-68c12ec6c6bd.jpg",
        label: "Earth Homes",
      },
      {
        image: "https://a0.muscache.com/pictures/c0fa9598-4e37-40f3-b734-4bd0e2377add.jpg",
        label: "Mensions",
      },
      {
        image: "https://a0.muscache.com/pictures/248f85bf-e35e-4dc3-a9a1-e1dbff9a3db4.jpg",
        label: "Villas",
      },
  ];
  
  

  export const homesData = [
    {
      image: [
        "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865202/bookmyhome/genrate1_aw7l9w.png",
        "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865199/bookmyhome/img18_my88gj.png",
        "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865202/bookmyhome/generate4_fowdlo.png",
        "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865200/bookmyhome/generate_17_nrpdx6.png",
      ],
      location: {
        city: "Jaunpur",
        country: "India",
      },
      distanceFromCity: 5,
      rentPerNight: {
        amount: 2500,
        currency: "INR",
      },
      ratings: 4.5,
      category: "appartment",
      guests: 4,
      rooms: 2,
      bedrooms: 2,
      bathrooms: 1,
      amenities: [
        "Wifi",
        "Free parking on premises",
        "TV",
        "Patio or balcony",
        "Garden",
        "Breakfast",
      ],
      unavailableAmenities: [
        "Carbon monoxide alarm",
        "Smoke alarm",
      ],
    },
    {
        image: [
             "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865202/bookmyhome/generate_6_xxxacx.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865199/bookmyhome/img18_my88gj.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865202/bookmyhome/generate4_fowdlo.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865200/bookmyhome/generate_17_nrpdx6.png",
          ],
      location: {
        city: "Allahabd",
        country: "India",
      },
      distanceFromCity: 5,
      rentPerNight: {
        amount: 1200,
        currency: "INR",
      },
      ratings: 4.0,
      category: "Private Room",
      guests: 2,
      rooms: 1,
      bedrooms: 1,
      bathrooms: 1,
      amenities: [
        "Wifi",
        "Free parking on premises",
        "TV",
        "Patio or balcony",
        "Breakfast",
      ],
      unavailableAmenities: [],
    },
    {
        image: [
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865200/bookmyhome/generate_12_zrvnea.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865202/bookmyhome/genrate1_aw7l9w.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865202/bookmyhome/generate4_fowdlo.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865200/bookmyhome/generate_17_nrpdx6.png",
          ],
      location: {
        city: "Varanasi",
        country: "India",
      },
      distanceFromCity: 4,
      rentPerNight: {
        amount: 3200,
        currency: "INR",
      },
      ratings: 2.8,
      category: "Private villa",
      guests: 2,
      rooms: 2,
      bedrooms: 1,
      bathrooms: 1,
      amenities: [
        "Wifi",
        "Free parking on premises",
        "TV",
        "Patio or balcony",
        "Breakfast",
      ],
      unavailableAmenities: [],
    },
    {
        image: [
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865202/bookmyhome/generate4_fowdlo.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865202/bookmyhome/genrate1_aw7l9w.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865199/bookmyhome/img18_my88gj.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865200/bookmyhome/generate_17_nrpdx6.png",
          ],
      location: {
        city: "Jhansi",
        country: "India",
      },
      distanceFromCity: 12,
      rentPerNight: {
        amount: 2800,
        currency: "INR",
      },
      ratings: 3.0,
      category: "Room",
      guests: 2,
      rooms: 1,
      bedrooms: 1,
      bathrooms: 1,
      amenities: [
        "Wifi",
        "Free parking on premises",
        "TV",
        "Patio or balcony",
        "Breakfast",
      ],
      unavailableAmenities: [],
    },
    {
        image: [
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865201/bookmyhome/generate_10_qlo0oz.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865199/bookmyhome/img18_my88gj.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865202/bookmyhome/generate4_fowdlo.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865200/bookmyhome/generate_17_nrpdx6.png",
          ],
      location: {
        city: "Allahabd",
        country: "India",
      },
      distanceFromCity: 9,
      rentPerNight: {
        amount: 1200,
        currency: "INR",
      },
      ratings: 4.0,
      category: "Private Room",
      guests: 2,
      rooms: 1,
      bedrooms: 1,
      bathrooms: 1,
      amenities: [
        "Wifi",
        "Free parking on premises",
        "TV",
        "Patio or balcony",
        "Breakfast",
      ],
      unavailableAmenities: [],
    },
    {
        image: [
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865200/bookmyhome/generate_17_nrpdx6.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865202/bookmyhome/genrate1_aw7l9w.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865199/bookmyhome/img18_my88gj.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865202/bookmyhome/generate4_fowdlo.png",
            
          ],
      location: {
        city: "Allahabd",
        country: "India",
      },
      distanceFromCity: 8,
      rentPerNight: {
        amount: 1200,
        currency: "INR",
      },
      ratings: 4.0,
      category: "Private Room",
      guests: 2,
      rooms: 1,
      bedrooms: 1,
      bathrooms: 1,
      amenities: [
        "Wifi",
        "Free parking on premises",
        "TV",
        "Patio or balcony",
        "Breakfast",
      ],
      unavailableAmenities: [],
    },
    {
        image: [
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865202/bookmyhome/genrate1_aw7l9w.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865199/bookmyhome/img18_my88gj.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865202/bookmyhome/generate4_fowdlo.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865200/bookmyhome/generate_17_nrpdx6.png",
          ],
      location: {
        city: "Rohtas, Sasaram",
        country: "India",
      },
      distanceFromCity: 8,
      rentPerNight: {
        amount: 1200,
        currency: "INR",
      },
      ratings: 4.0,
      category: "Private Room",
      guests: 2,
      rooms: 1,
      bedrooms: 1,
      bathrooms: 1,
      amenities: [
        "Wifi",
        "Free parking on premises",
        "TV",
        "Patio or balcony",
        "Breakfast",
      ],
      unavailableAmenities: [],
    },
    {
        image: [
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865201/bookmyhome/generate_13_xj5apc.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865199/bookmyhome/img18_my88gj.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865202/bookmyhome/generate4_fowdlo.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865200/bookmyhome/generate_17_nrpdx6.png",
          ],
      location: {
        city: "Patna",
        country: "India",
      },
      distanceFromCity: 8,
      rentPerNight: {
        amount: 1200,
        currency: "INR",
      },
      ratings: 4.0,
      category: "Private Room",
      guests: 2,
      rooms: 1,
      bedrooms: 1,
      bathrooms: 1,
      amenities: [
        "Wifi",
        "Free parking on premises",
        "TV",
        "Patio or balcony",
        "Breakfast",
      ],
      unavailableAmenities: [],
    },
    {
        image: [
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865201/bookmyhome/generate_7_imuvo4.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865199/bookmyhome/img18_my88gj.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865202/bookmyhome/generate4_fowdlo.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865200/bookmyhome/generate_17_nrpdx6.png",
          ],
      location: {
        city: "Devghar",
        country: "India",
      },
      distanceFromCity: 8,
      rentPerNight: {
        amount: 1200,
        currency: "INR",
      },
      ratings: 4.0,
      category: "Private Room",
      guests: 2,
      rooms: 1,
      bedrooms: 1,
      bathrooms: 1,
      amenities: [
        "Wifi",
        "Free parking on premises",
        "TV",
        "Patio or balcony",
        "Breakfast",
      ],
      unavailableAmenities: [],
    },
    {
        image: [
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865201/bookmyhome/generate_9_ndktsd.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865199/bookmyhome/img18_my88gj.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865202/bookmyhome/generate4_fowdlo.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865200/bookmyhome/generate_17_nrpdx6.png",
          ],
      location: {
        city: "Ara",
        country: "India",
      },
      distanceFromCity: 8,
      rentPerNight: {
        amount: 1200,
        currency: "INR",
      },
      ratings: 4.0,
      category: "Private Room",
      guests: 2,
      rooms: 1,
      bedrooms: 1,
      bathrooms: 1,
      amenities: [
        "Wifi",
        "Free parking on premises",
        "TV",
        "Patio or balcony",
        "Breakfast",
      ],
      unavailableAmenities: [],
    },
    {
        image: [
             "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865202/bookmyhome/generate_6_xxxacx.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865199/bookmyhome/img18_my88gj.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865202/bookmyhome/generate4_fowdlo.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865200/bookmyhome/generate_17_nrpdx6.png",
          ],
      location: {
        city: "Allahabd",
        country: "India",
      },
      distanceFromCity: 8,
      rentPerNight: {
        amount: 1200,
        currency: "INR",
      },
      ratings: 4.0,
      category: "Private Room",
      guests: 2,
      rooms: 1,
      bedrooms: 1,
      bathrooms: 1,
      amenities: [
        "Wifi",
        "Free parking on premises",
        "TV",
        "Patio or balcony",
        "Breakfast",
      ],
      unavailableAmenities: [],
    },
    {
        image: [
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865201/bookmyhome/generate_8_nfa8yy.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865199/bookmyhome/img18_my88gj.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865202/bookmyhome/generate4_fowdlo.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865200/bookmyhome/generate_17_nrpdx6.png",
          ],
      location: {
        city: "Allahabd",
        country: "India",
      },
      distanceFromCity: 8,
      rentPerNight: {
        amount: 1200,
        currency: "INR",
      },
      ratings: 4.0,
      category: "Private Room",
      guests: 2,
      rooms: 1,
      bedrooms: 1,
      bathrooms: 1,
      amenities: [
        "Wifi",
        "Free parking on premises",
        "TV",
        "Patio or balcony",
        "Breakfast",
      ],
      unavailableAmenities: [],
    },
    {
        image: [
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865201/bookmyhome/generate_15_e454um.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865199/bookmyhome/img18_my88gj.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865202/bookmyhome/generate4_fowdlo.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865200/bookmyhome/generate_17_nrpdx6.png",
          ],
      location: {
        city: "Allahabd",
        country: "India",
      },
      distanceFromCity: 8,
      rentPerNight: {
        amount: 1200,
        currency: "INR",
      },
      ratings: 4.0,
      category: "Private Room",
      guests: 2,
      rooms: 1,
      bedrooms: 1,
      bathrooms: 1,
      amenities: [
        "Wifi",
        "Free parking on premises",
        "TV",
        "Patio or balcony",
        "Breakfast",
      ],
      unavailableAmenities: [],
    },
    {
        image: [
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865201/bookmyhome/generate_10_qlo0oz.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865199/bookmyhome/img18_my88gj.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865202/bookmyhome/generate4_fowdlo.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865200/bookmyhome/generate_17_nrpdx6.png",
          ],
      location: {
        city: "Allahabd",
        country: "India",
      },
      distanceFromCity: 8,
      rentPerNight: {
        amount: 1200,
        currency: "INR",
      },
      ratings: 4.0,
      category: "Private Room",
      guests: 2,
      rooms: 1,
      bedrooms: 1,
      bathrooms: 1,
      amenities: [
        "Wifi",
        "Free parking on premises",
        "TV",
        "Patio or balcony",
        "Breakfast",
      ],
      unavailableAmenities: [],
    },
    {
        image: [
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865200/bookmyhome/generate_14_pm0zki.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865199/bookmyhome/img18_my88gj.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865202/bookmyhome/generate4_fowdlo.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865200/bookmyhome/generate_17_nrpdx6.png",
          ],
      location: {
        city: "Allahabd",
        country: "India",
      },
      distanceFromCity: 8,
      rentPerNight: {
        amount: 1200,
        currency: "INR",
      },
      ratings: 4.0,
      category: "Private Room",
      guests: 2,
      rooms: 1,
      bedrooms: 1,
      bathrooms: 1,
      amenities: [
        "Wifi",
        "Free parking on premises",
        "TV",
        "Patio or balcony",
        "Breakfast",
      ],
      unavailableAmenities: [],
    },
    {
        image: [
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865200/bookmyhome/generate_16_yi1vnp.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865199/bookmyhome/img18_my88gj.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865202/bookmyhome/generate4_fowdlo.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865200/bookmyhome/generate_17_nrpdx6.png",
          ],
      location: {
        city: "Allahabd",
        country: "India",
      },
      distanceFromCity: 8,
      rentPerNight: {
        amount: 1200,
        currency: "INR",
      },
      ratings: 4.0,
      category: "Private Room",
      guests: 2,
      rooms: 1,
      bedrooms: 1,
      bathrooms: 1,
      amenities: [
        "Wifi",
        "Free parking on premises",
        "TV",
        "Patio or balcony",
        "Breakfast",
      ],
      unavailableAmenities: [],
    },
    {
        image: [
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865200/bookmyhome/generate_11_zrqase.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865199/bookmyhome/img18_my88gj.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865202/bookmyhome/generate4_fowdlo.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865200/bookmyhome/generate_17_nrpdx6.png",
          ],
      location: {
        city: "Allahabd",
        country: "India",
      },
      distanceFromCity: 8,
      rentPerNight: {
        amount: 1200,
        currency: "INR",
      },
      ratings: 4.0,
      category: "Private Room",
      guests: 2,
      rooms: 1,
      bedrooms: 1,
      bathrooms: 1,
      amenities: [
        "Wifi",
        "Free parking on premises",
        "TV",
        "Patio or balcony",
        "Breakfast",
      ],
      unavailableAmenities: [],
    },
    {
        image: [
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865199/bookmyhome/generate_18_d2r6lh.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865199/bookmyhome/img18_my88gj.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865202/bookmyhome/generate4_fowdlo.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865200/bookmyhome/generate_17_nrpdx6.png",
          ],
      location: {
        city: "Allahabd",
        country: "India",
      },
      distanceFromCity: 8,
      rentPerNight: {
        amount: 1200,
        currency: "INR",
      },
      ratings: 4.0,
      category: "Private Room",
      guests: 2,
      rooms: 1,
      bedrooms: 1,
      bathrooms: 1,
      amenities: [
        "Wifi",
        "Free parking on premises",
        "TV",
        "Patio or balcony",
        "Breakfast",
      ],
      unavailableAmenities: [],
    },
    {
        image: [
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865200/bookmyhome/generate_17_nrpdx6.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865199/bookmyhome/img18_my88gj.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865202/bookmyhome/generate4_fowdlo.png",
            "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865200/bookmyhome/generate_17_nrpdx6.png",
          ],
      location: {
        city: "Allahabd",
        country: "India",
      },
      distanceFromCity: 8,
      rentPerNight: {
        amount: 1200,
        currency: "INR",
      },
      ratings: 4.0,
      category: "Private Room",
      guests: 2,
      rooms: 1,
      bedrooms: 1,
      bathrooms: 1,
      amenities: [
        "Wifi",
        "Free parking on premises",
        "TV",
        "Patio or balcony",
        "Breakfast",
      ],
      unavailableAmenities: [],
    },
    // Repeat similar structure for other entries
    // ...
  ];
  
  
  const img1 =[
    "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865202/bookmyhome/genrate1_aw7l9w.png",
    "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865202/bookmyhome/generate_6_xxxacx.png",
    "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865202/bookmyhome/generate2_eewrl6.png",
    "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865202/bookmyhome/generate4_fowdlo.png",
    "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865202/bookmyhome/generate_5_roqhrr.png",
    "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865202/bookmyhome/generate3_sd1qng.png",
    "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865201/bookmyhome/generate_13_xj5apc.png",
    "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865201/bookmyhome/generate_7_imuvo4.png",
    "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865201/bookmyhome/generate_9_ndktsd.png",
    "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865201/bookmyhome/generate_8_nfa8yy.png",
    "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865201/bookmyhome/generate_15_e454um.png",
    "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865201/bookmyhome/generate_10_qlo0oz.png",
    "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865200/bookmyhome/generate_14_pm0zki.png",
    "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865200/bookmyhome/generate_16_yi1vnp.png",
    "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865200/bookmyhome/generate_11_zrqase.png",
    "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865199/bookmyhome/generate_18_d2r6lh.png",
    "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865200/bookmyhome/generate_17_nrpdx6.png",
    "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865200/bookmyhome/generate_12_zrvnea.png",
    "https://res.cloudinary.com/dzxyaeoyz/image/upload/v1698865199/bookmyhome/img18_my88gj.png"
  ]